---
url: http://example.com/receive
method: PUT
body:
  bodyone: |
    {
      "properties": {
        "ServerIP": {
          "type":     "text",
          "fielddata": true
        }
      }
    }
  bodytwo: |
    {
      "properties": {
        "ServerIP": {
          "type":     "text",
          "fielddata": true
        }
      }
    }
range:
  hour:
    gte: 0
    lte: 13
run_every:
  seconds: 30

---
url: http://example2.com/receive
method: GET
body:
  bodyone2: |
    {
      "properties": {
        "ServerIP": {
          "type":     "text",
          "fielddata": true
        }
      }
    }
range:
  hour:
    gte: 8
    lte: 13
  month:
    gte: 10
    lte: 11
  weekday:
    gte: 0
    lte: 3
run_every:
  seconds: 30