---
url: http://example.com/receive
method: PUT
header:
  Accept: application/json, text/plain, */*
  Referer: http://vinkdong.com/
body:
  bodyone: |
    {
      "properties": {
        "ServerIP": {
          "type":     "text",
          "fielddata": true
        }
      }
    }
  bodytwo: |
    {
      "properties": {
        "ServerIP": {
          "type":     "text",
          "fielddata": true
        }
      }
    }
log_response: false
range:
  hour:
    gte: 0
    lte: 13
run_every:
  seconds: 30
checker:
  - type: json
    rule:
      - $.status = "green"
      - $.number_of_data_nodes = 2

---
url: https://vinkdong.com
method: GET
header:
  Accept: application/json, text/plain, */*
  Referer: http://vinkdong.com/
body:
  bodyone2: |
    {
      "properties": {
        "ServerIP": {
          "type":     "text",
          "fielddata": true
        }
      }
    }
range:
  hour:
    gte: 8
    lte: 13
  month:
    gte: 10
    lte: 12
  weekday:
    gte: 0
    lte: 5
run_every:
  seconds: 30