---
url: http://example.com/receive
method: PUT
body:
  bodyone: |
    {
      "properties": {
        "ServerIP": {
          "type":     "text",
          "fielddata": true
        }
      }
    }
  bodytwo: |
    {
      "properties": {
        "ServerIP": {
          "type":     "text",
          "fielddata": true
        }
      }
    }
range:
  hour:
    gte: 10
    lte: 13
run_every:
  seconds: 10