---
apiVersion: v1
kind: ConfigMap
metadata:
  name: timing-request
data:
  config.yaml: |
    ---
    url: http://elasticsearch.logging.svc
    method: PUT
    body:
      bodyone: |
        {
          "properties": {
            "ServerIP": {
              "type":     "text",
              "fielddata": true
            }
          }
        }
      bodytwo: |
        {
          "properties": {
            "ServerIP": {
              "type":     "text",
              "fielddata": true
            }
          }
        }
    range:
      hour:
        gte: 0
        lte: 12
    run_every:
      minutes: 5

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: timing-request
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: timing-request
    spec:
      volumes:
        - name: config
          configMap:
            name:  timing-request
            items:
              - key: config.yaml
                path: config.yaml
            defaultMode: 420
      containers:
      - name: timing-request
        image: hand/timing_request
        volumeMounts:
            - name: config
              mountPath: /timingconf
        ports:
        - containerPort: 9800
          protocol: TCP

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: timing-request
  annotations:
    prometheus.io/scrape: 'true'
  name: timing-request
spec:
  ports:
  - port: 9800
    targetPort: 9800
    protocol: TCP
  selector:
    name: timing-request